### PR TITLE
Add missing environment variables

### PR DESCRIPTION
**Pull request by harmtemolder**
I went through the Pixelfed code and Admin > Diagnostics and added everything I could find to Technical documentation > Configuration. This helped me to get a clear picture of what variables I could set in my `.env` and what they mean. I hope it will help others too.

### CODE REVIEW

**Comment by harmtemolder** [comment]
This might actually be what you were asking for here: https://github.com/pixelfed/docs/projects/1#card-32158347

**Comment by trwnh** [comment]
Thank you for going through the code! This is very much appreciated. There are some minor formatting preferences I'd change, but that can be done in a follow-up PR. :)

**Comment by harmtemolder** [comment]
Ow, you were fast. I noticed the sections I added weren't ordered alphabetically yet, so I fixed that, but only after you merged this PR.

What are the minor formatting preferences? I could change those too, then do a follow-up

**Comment by trwnh** [comment]
Ah, heh, yeah. It would be my preference to not use footnotes, but to instead inline this information as part of the text underneath each variable's heading, in the same line as descriptions and default values.

**Pull request merged**
